name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -t andkol90/skypro_andkol:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
        #также как и локально собирали бы докер контейнер
      - name: login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push andkol90/skypro_andkol:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: clone code
          uses: actions/checkout@v2
        - name: render_configs
          run: |
            mkdir deploy
            type docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
        - name: copy files to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            source: "deploy/docker-compose.yaml"
            target: "flask_app_ci"
            strip_components: 1

